### ISSUE TITLE
关于EnableResizing宏的问题

### ISSUE THREAD

**Issue by CTRTiger** [zouhuidong/HiEasyX#10]
我想要禁止改变窗口大小，但是使用EnableResizing(GetHWnd(), false);之后生成的窗口是鼠标穿透的，没法交互，不知道是我的打开方式不对还是bug。

代码：
`#include"HiEasyX.h"
#include<iostream>
#include<cstdio>
#include<cstdlib>
#include<cstring>
#include<string.h>
#include<conio.h>

hiex::Window VirtualVisualWindow; //窗口

int main()
{
	//创建窗口，取消后台
	VirtualVisualWindow.Create(924, 520,NULL,_T("Test")); //创建窗口
	hiex::AutoExit(); //无后台
	EnableResizing(GetHWnd(), false); //禁止改变大小
        _getch();
	return 0;
}`

**Comment by zouhuidong** [comment]
按照你的代码实测没有这个问题（Win10 + VS 2022 + HiEasyX Ver 0.3.0）

有可能是你的 HiEasyX 版本太旧了，升级到 Ver 0.2.2 或者 Ver 0.3.0 再试试？

Ver 0.3.0 改动比较大，如果你的版本低于 Ver 0.2.2，先升级到 Ver 0.2.2 试试，在 [这里](https://github.com/zouhuidong/HiEasyX/releases/tag/Ver0.2.2)

**Comment by zouhuidong** [comment]
更新：

我已经测试过所有版本的 HiEasyX 了，均不能复现你的问题。

你是用的什么系统、什么版本的 HiEasyX 呢？你所给出的这段代码在你那能否复现问题呢？因为我只能完全根据你给出的代码进行测试，所以我觉得可能是你这段代码不足以复现问题。
