### ISSUE TITLE
关于无法使用Canvas加载文件图像并绘制的问题

### ISSUE THREAD

**Issue by Friman04** [zouhuidong/HiEasyX#12]
大一新生，刚学C语言没多久，没学过C++

`/*******************************************
 * @date    2023.01.12
 * @envir	Windows 11 dev_Build 25272.rs_prerelease.221216-1237 | Visual Studio 2022 | EasyX_20220901
 * @ver     0.1alpha
 *
 *******************************************/

#define _CRT_SECURE_NO_WARNINGS

#include <io.h>
#include <stdio.h>
#include <direct.h>

#define MAX_LEN 4096
#include <stdio.h>
#include <string.h>
#include "HiEasyX.h"
//#include<graphics.h>

#ifdef UNICODE  //设置多字节字符集
#undef UNICODE
#endif

// 窗体大小
#define ASPECT_RATIO 1.778                  // 宽高比
#define WINDOW_HEI 720                      // 窗体高度大小
#define WINDOW_WID WINDOW_HEI*ASPECT_RATIO  // 窗体宽度大小

#define PHI 0.618
#define EX_LEFT (PHI - 0.5) / 2
#define MID_LEFT (1 - PHI) / 2

// 字体居中
#define TOP_LEFT     1
#define TOP          2
#define TOP_RIGHT    3
#define LEFT         4
#define CENTER       5
#define RIGHT        6
#define BOTTOM_LEFT  7
#define BOTTOM       8
#define BOTTOM_RIGHT 9

char token; // 未使用

typedef struct
{
	char id[16];
	char pwd[20];
	int value1;
	int value2;
	int sex;
}user;

typedef struct
{int x, y;}intPair;

// 函数区

/**
 * @brief 计算对齐坐标
 * @param[in] x		            背景对象的x坐标
 * @param[in] y			        背景对象的y坐标
 * @param[in] w		            背景对象的宽度
 * @param[in] h			        背景对象的高度
 * @param[in] wid				被绘制对象的宽度
 * @param[in] hei   			被绘制对象的高度
 * @param[in] align_mode   		对齐方式（默认居中对齐）
 * @return                      被绘制对象的坐标
*/
intPair align(int x, int y, int w, int h, int wid, int hei, int align_mode = CENTER)
{
    intPair pos;
    switch (align_mode)
    {
        case 1:
        {
            pos.x = x;
            pos.y = y;
            return pos;
        }
        case 2:
        {
            pos.x = x + w / 2 - wid / 2;
            pos.y = y;
            return pos;
        }
        case 3:
        {
            pos.x = x + w - wid;
            pos.y = y;
            return pos;
        }
        case 4:
        {
            pos.x = x;
            pos.y = y + h / 2 - hei / 2;
            return pos;
        }
        case 5:
        {
            pos.x = x + w / 2 - wid / 2,
            pos.y = y + h / 2 - hei / 2;
            return pos;
        }
        case 6:
        {
            pos.x = x + w - wid;
            pos.y = y + h / 2 - hei / 2;
            return pos;
        }
        case 7:
        {
            pos.x = x;
            pos.y = y + h - hei;
            return pos;
        }
        case 8:
        {
            pos.x = x + w / 2 - wid / 2;
            pos.y = y + h - hei;
            return pos;
        }
        case 9:
        {
            pos.x = x + w - wid;
            pos.y = y + h - hei;
            return pos;
        }
    }
}

/**
 * @brief 在矩形区域内加载图像文件并对齐绘制
 * @param[in] canvas		    Canvas类的实例化
 * @param[in] img_file			图片文件位置
 * @param[in] iWidth			图片目标拉伸宽度（为0表示不拉伸）
 * @param[in] iHeight		    图片目标拉伸高度（为0表示不拉伸）
 * @param[in] pivot_x			锚点x坐标（即区域左上角x坐标）
 * @param[in] pivot_y			锚点y坐标（即区域左上角y坐标）
 * @param[in] wid				区域宽度
 * @param[in] hei   			区域高度
 * @param[in] align_mode   		对齐方式（默认居中对齐）
 * @param[in] alpha	            叠加透明度（默认透明度100%/255U）
 * @param[in] isAlpha       	是否开启混合图像透明通道（默认是）
 * @return                      读取到的IMAGE对象
*/
IMAGE imageAlign_alpha(hiex::Canvas& canvas,
                       LPCTSTR img_file,
                       int iWidth,
                       int iHeight,
                       int pivot_x,
                       int pivot_y,
                       int wid,
                       int hei,
                       int align_mode = CENTER,
                       BYTE alpha = 255U,
                       bool isAlpha = true)
{
    // 锚点应设置在区域的左上角
    IMAGE img;
    intPair text_pos = align(pivot_x, pivot_y, wid, hei, iWidth, iHeight, align_mode);
    img = canvas.Load_Image_Alpha(img_file, text_pos.x, text_pos.y, false, iWidth, iHeight, alpha, isAlpha);
    return img;
}

/**
 * @brief 在矩形区域内对齐绘制文字
 * @param[in] canvas		    Canvas类的实例化
 * @param[in] str			    绘制的字符串
 * @param[in] fHeight		    字符高度
 * @param[in] fWidth			字符宽度（如果值为0，则字符串自适应间距）
 * @param[in] font  			字体
 * @param[in] pivot_x			锚点x坐标（即区域左上角x坐标）
 * @param[in] pivot_y			锚点y坐标（即区域左上角y坐标）
 * @param[in] wid				区域宽度
 * @param[in] hei   			区域高度
 * @param[in] align_mode   		对齐方式（默认居中对齐）
 * @param[in] c	                字体颜色
 * @param[in] esc       		字符串的书写角度（单位0.1°）
 * @param[in] ori         		每个字符的书写角度（单位0.1°）
*/
void textAlign(hiex::Canvas& canvas,
               LPCTSTR str,
               int fHeight,
               int fWidth,
               LPCTSTR font,
               int pivot_x,
               int pivot_y,
               int wid,
               int hei,
               int align_mode = CENTER,
               COLORREF c = BLACK,
               LONG esc = 0,
               LONG ori = 0,
               int bg = TRANSPARENT)
{
    // 锚点应设置在区域的左上角
    canvas.SetTextEscapement(esc);
    canvas.SetTextOrientation(ori);
    canvas.SetBkMode(bg);
    canvas.SetTextStyle(fHeight, fWidth, font);

    intPair text_pos = align(pivot_x, pivot_y, wid, hei, canvas.TextWidth(str), canvas.TextHeight(str), align_mode);
    canvas.OutTextXY(text_pos.x, text_pos.y, str, true, c);
}

/**
 * @brief 在矩形区域内对齐绘制文字
 * @param[in] canvas		    Canvas类的实例化
 * @param[in] str			    绘制的字符串
 * @param[in] fHeight		    字符宽度
 * @param[in] fWidth			字符宽度（如果值为0，则字符串自适应间距）
 * @param[in] font  			字体
 * @param[in] pivot_x			锚点x坐标（即区域左上角x坐标）
 * @param[in] pivot_y			锚点y坐标（即区域左上角y坐标）
 * @param[in] wid				区域宽度
 * @param[in] hei   			区域高度
 * @param[in] align_mode   		对齐方式（默认居中对齐）
 * @param[in] c	                字体颜色
 * @param[in] esc       		字符串的书写角度（单位0.1°）
 * @param[in] ori         		每个字符的书写角度（单位0.1°）
*/
void __TextAlign(hiex::Canvas & canvas,
                 LPCTSTR str,
                 int fHeight,
                 int fWidth,
                 LPCTSTR font,
                 int pivot_x,
                 int pivot_y,
                 int wid,
                 int hei,
                 int align_mode = CENTER,
                 COLORREF c = BLACK,
                 LONG esc = 0,
                 LONG ori = 0,
                 int bg = TRANSPARENT)
{
    // 锚点应设置在区域的左上角

    canvas.SetTextEscapement(esc);
    canvas.SetTextOrientation(ori);
    canvas.SetBkMode(bg);
    canvas.SetTextStyle(fHeight, fWidth, font);
    switch (align_mode)
    {
    case 1:
        canvas.OutTextXY(pivot_x, pivot_y, str, true, c);
        break;
    case 2:
        canvas.OutTextXY(
            pivot_x + wid / 2 - canvas.TextWidth(str) / 2,
            pivot_y,
            str,
            true, c);
        break;
    case 3:
        canvas.OutTextXY(
            pivot_x + wid - canvas.TextWidth(str),
            pivot_y,
            str,
            true, c);
        break;
    case 4:
        canvas.OutTextXY(
            pivot_x,
            pivot_y + wid / 2 - canvas.TextHeight(str) / 2,
            str,
            true, c);
        break;
    case 5:
        canvas.OutTextXY(
            pivot_x + wid / 2 - canvas.TextWidth(str) / 2,
            pivot_y + hei / 2 - canvas.TextHeight(str) / 2,
            str,
            true, c);
        break;
    case 6:
        canvas.OutTextXY(
            pivot_x + wid - canvas.TextWidth(str),
            pivot_y + hei / 2 - canvas.TextHeight(str) / 2,
            str,
            true, c);
        break;
    case 7:
        canvas.OutTextXY(
            pivot_x,
            pivot_y + hei - canvas.TextHeight(str),
            str,
            true, c);
        break;

    case 8:
        canvas.OutTextXY(
            pivot_x + wid / 2 - canvas.TextWidth(str) / 2,
            pivot_y + hei - canvas.TextHeight(str),
            str,
            true, c);
        break;
    case 9:
        canvas.OutTextXY(
            pivot_x + wid - canvas.TextWidth(str),
            pivot_y + hei - canvas.TextHeight(str),
            str,
            true, c);
        break;
    }
}

/**
 * @deprecated 此函数已经过时
 * @brief 在矩形中对齐绘制文字
 * @param[in] x				    矩形左上角x坐标
 * @param[in] y				    矩形左上角y坐标
 * @param[in] width				矩形宽度
 * @param[in] height			矩形高度
 * @param[in] horizontal	    是否水平居中（默认是）
 * @param[in] vertical  		是否垂直居中（默认是）
*/
void __textAlign(LPCTSTR str, int x, int y, int width, int height, bool horizontal = true, bool vertical = true, int mode = TRANSPARENT)
{

    LOGFONT font;
    setbkmode(mode);
    gettextstyle(&font);
    int textHeight = font.lfHeight;
    int textWidth = textHeight;
    int strWidth = 0;
    int strNum = lstrlen(str);
    for (int i = 0; i < strNum; ++i)
        strWidth += (str[i] > 127) ? textHeight : textHeight / 2;
    if (strWidth >= width || textHeight >= height)
    {
        outtextxy(x, y, str);
        return;
    }
    if (horizontal)
        x += (width - strWidth) / 2;
    if (vertical)
        y += (height - textHeight) / 2;
    outtextxy(x, y, str);
}

//---------------------------------------------------------------------------------------------------------------------------------
// 出问题的函数
//---------------------------------------------------------------------------------------------------------------------------------

void home()
{

    hiex::Canvas canvas_main;
    //hiex::Scene scene_btn;
    //hiex::Layer layer_btn;
    //hiex::ImageBlock btn;
    hiex::Window wnd(WINDOW_WID, WINDOW_HEI);
    wnd.BindCanvas(&canvas_main);
    hiex::AutoExit();
    HWND hwnd = wnd.GetHandle();

    while (1)
    {
        /*绘制GUI框架*/

        char root[] = "data";
        struct _finddata_t file;
        intptr_t hFile;
        char buf[MAX_LEN];

        if (_chdir(root)){printf("打开文件夹失败: %s\n", root);}         ///<-------注释掉这行即正常绘制图片

        hFile = _findfirst("*.txt", &file);
        if (hFile == -1)
            printf("没有找到文件！\n");
        while (_findnext(hFile, &file) == 0)
        {
            sprintf_s(buf, MAX_LEN, "%s\\%s", root, file.name);
            printf("%s\n", buf);
        }

        /*
        edit.PreSetStyle(true, false, true);
        edit.Create(hwnd, WINDOW_WID * EX_LEFT, WINDOW_WID * EX_LEFT, WINDOW_WID * (MID_LEFT - EX_LEFT), WINDOW_HEI - WINDOW_WID * EX_LEFT,
            L"Welcome to HiEasyX !\r\n"
            L"\r\n"
            L"Here you will experience the overall upgrade of EasyX.\r\n"
            L"Let's start HiEasyX from the simple sample.\r\n"
            L"\r\n"
            L"What's new in HiEasyX\r\n"
            L"\r\n"
            L">> You could create multi-window application with HiEasyX easily.\r\n"
            L">> You could use HiCanvas, which is a C++ canvas wrapper of EasyX, in the similar way of EasyX.\r\n"
            L">> The best support of Windows system controls integrated in HiEasyX is avalible.\r\n"
            L">> The most easy method to create a tray.\r\n"
            L"etc.\r\n"
        );
        edit.SetFont(26, 0, L"微软雅黑");
        */
        

        // 背景1
        canvas_main.Clear(true, WHITE);  //设置背景颜色

        // 线条
        canvas_main.SetLineStyle(PS_SOLID, 2);
        canvas_main.SetLineColor(0xEEEEEE);
        canvas_main.Line(WINDOW_WID * MID_LEFT, WINDOW_WID * EX_LEFT, WINDOW_WID * MID_LEFT, WINDOW_HEI); // 分隔资源管理器和绘图区

        // 背景2
        canvas_main.SetFillColor(0x662015);
        canvas_main.FillRectangle(0, 0, WINDOW_WID * EX_LEFT, WINDOW_HEI); // 左侧深蓝色背景
        canvas_main.SetFillColor(0xEFE1CF);
        canvas_main.FillRectangle(0, 0, WINDOW_WID, WINDOW_WID * EX_LEFT); // 顶侧浅蓝色背景

        //logo
        canvas_main.Load_Image_Alpha(L"sprites/logo_light.png", 0, 0, false, WINDOW_WID * EX_LEFT - 1, WINDOW_WID * EX_LEFT - 1, 255U, true);

        // 文字
        textAlign(canvas_main, L"工业数据分析与文件信息管理系统", 36, 0, L"微软雅黑", WINDOW_WID * EX_LEFT, 0, WINDOW_WID * (1 - EX_LEFT), WINDOW_WID * EX_LEFT); // 标题
        textAlign(canvas_main, L"Created by Friman " _SYS_VER_STR_, 16, 0, L"Arial", 0, 0, WINDOW_WID, WINDOW_HEI, BOTTOM_RIGHT, GRAY); // 信息

        // 按钮绘制

        imageAlign_alpha(canvas_main, L"sprites/login.png", 32, 32, WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * EX_LEFT / 2, WINDOW_WID * EX_LEFT / 2);
        REDRAW_WINDOW();
        //按钮控件逻辑

        ExMessage m_msg;
        while (1)
        {   
            
            m_msg = getmessage(EX_MOUSE);
            
            
            if (m_msg.x > WINDOW_WID * (1 - EX_LEFT * 3 / 4) && m_msg.y > WINDOW_WID * EX_LEFT / 4 && m_msg.x < WINDOW_WID * (1 - EX_LEFT / 4) && m_msg.y < WINDOW_WID * EX_LEFT * 3 / 4) // 如果鼠标在这个区间内
            {
                switch (m_msg.message)
                {
                    case WM_LBUTTONDOWN:
                    {
                        canvas_main.SetFillColor(YELLOW);
                        canvas_main.FillRoundRect(WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * (1 - EX_LEFT / 4), WINDOW_WID * EX_LEFT * 3 / 4, 20, 20);
                        imageAlign_alpha(canvas_main, L"sprites/login.png", 32, 32, WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * EX_LEFT / 2, WINDOW_WID * EX_LEFT / 2);
                        REDRAW_WINDOW();
                        break;
                    }
                    case WM_LBUTTONUP:
                    {
                        textAlign(canvas_main, _T("TEST"), 36, 0, _T("微软雅黑"), 0, 0, WINDOW_WID, WINDOW_WID); //do somthing
                        canvas_main.SetFillColor(BLUE);
                        canvas_main.FillRoundRect(WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * (1 - EX_LEFT / 4), WINDOW_WID * EX_LEFT * 3 / 4, 20, 20);
                        imageAlign_alpha(canvas_main, L"sprites/login.png", 32, 32, WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * EX_LEFT / 2, WINDOW_WID * EX_LEFT / 2);
                        REDRAW_WINDOW();
                        break;
                    }
                    default:
                    {
                        // 鼠标指针经过按钮
                        canvas_main.SetFillColor(LIGHTBLUE);
                        canvas_main.FillRoundRect(WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * (1 - EX_LEFT / 4), WINDOW_WID * EX_LEFT * 3 / 4, 20, 20);
                        imageAlign_alpha(canvas_main, L"sprites/login.png", 32, 32, WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * EX_LEFT / 2, WINDOW_WID * EX_LEFT / 2);
                        REDRAW_WINDOW();
                        break;
                    }
                }
            }
            else
            {
                // 默认状态
                canvas_main.ClearRoundRect(WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * (1 - EX_LEFT / 4), WINDOW_WID * EX_LEFT * 3 / 4, 20, 20);
                imageAlign_alpha(canvas_main, L"sprites/login.png", 32, 32, WINDOW_WID * (1 - EX_LEFT * 3 / 4), WINDOW_WID * EX_LEFT / 4, WINDOW_WID * EX_LEFT / 2, WINDOW_WID * EX_LEFT / 2);
                REDRAW_WINDOW();
            }
        }

        hiex::init_end(hwnd);
		break;
	}
}

int main()
{   

	home();

    getchar();
	return 0;
}`
左上角图片不显示
![image](https://user-images.githubusercontent.com/117433288/212543407-789c1411-14d5-4123-8e38-cea1e63fc1ca.png)
左上角t图片显示
![image](https://user-images.githubusercontent.com/117433288/212543453-83d4b775-36f0-4676-8153-96fb7a93049f.png)

**Comment by zouhuidong** [comment]
你给了两张效果图片，我的理解是：第一张是代码实际的运行效果，第二张是你期望的运行效果，对吗？我暂且这么理解。

你问的问题是有关图片加载的问题，但是你却只给代码，不给图片资源，这让我很困扰。我不知道你的图片路径是否正确，也不知道图片是否带有透明度。

以下是我只根据代码进行的推断。
你的代码中有一行：
```cpp
//logo
canvas_main.Load_Image_Alpha(L"sprites/logo_light.png", 0, 0, false, WINDOW_WID * EX_LEFT - 1, WINDOW_WID * EX_LEFT - 1, 255U, true);
```
在此处，你调用 Canvas::Load_Image_Alpha 时，设置了参数 bUseSrcColor（也就是最后一个参数）为 true，试试设为 false？
或者，将上面那行代码改为：
```cpp
// 尝试先把图片加载到 IMAGE 中，再输出到画布
// 如果还是不行，可以打断点看看 imgLogo 到底是否读入了图片
// 若 imgLogo 的宽高为 0，则说明读入失败
IMAGE imgLogo;
loadimage(&imgLogo, L"sprites/logo_light.png");
canvas_main.PutImageIn_Alpha(0, 0, &imgLogo);
```

如果问题还没有解决，希望你可以把项目打包发出来（打包时记得删去 .vs，debug，release，x64 等无关文件夹），否则，只有源代码，我无法运行你的程序。

**Comment by zouhuidong** [comment]
我给你写了一个能正确加载图片的示例，以下的压缩包中含有完整的项目，可以直接编译运行。

你可以先对比看看，为什么你的代码不能加载出图片。

[HiEasyX-main.zip](https://github.com/zouhuidong/HiEasyX/files/10422948/HiEasyX-main.zip)
