### ISSUE TITLE
[ 询问 ] TDM-GCC编译器可以使用吗？

### ISSUE THREAD

**Issue by Satan123231** [zouhuidong/HiEasyX#13]
TDM-GCC编译器可以使用吗？我是VScode + TDM-GCC一起使用的，之前用的easyx也是用的easyX for MinGW

**Comment by zouhuidong** [comment]
应该不行，我只用 Visual Studio 2019 / 2022 实测过。不过你可以试试，注意编译时要选用 Unicode 字符集。

**Comment by Satan123231** [comment]
![image](https://user-images.githubusercontent.com/41412981/217863807-85668d6d-b612-481a-8006-292bae6c4248.png)
TDM-GCC似乎对于很多都不支持

**Comment by zouhuidong** [comment]
你这里全都是 wchar_t 和 LPCTSTR 的问题，应该是没有设置 unicode 字符集编译吧？我不太懂 gcc，不知道能否像 VS 那样设置项目字符集为 Unicode？

**Comment by zouhuidong** [comment]
此 issue 转到：https://github.com/zouhuidong/HiEasyX/issues/14

**Comment by Alan-CRL** [comment]
好消息：HiEasyX 现已同时支持 Unicode 和 MBCS 字符集，同时支持 MSVC、MinGW、TDM-GCC 等编译器
