### ISSUE TITLE
[ MinGW ] HiEasyX 什么时候支持 MinGW？

### ISSUE THREAD

**Issue by F1A-in-wonder** [zouhuidong/HiEasyX#14]
什么时候可以支持MinGW编译器啊（期待）

**Comment by Satan123231** [comment]
同求

**Comment by zouhuidong** [comment]
抱歉，学业繁忙，没能及时回复。暂时还不能支持 MinGW，有如下原因：
1. MinGW 相对于 VS 比较小众，EasyX 自零几年发布以来，十多年都未曾支持 MinGW，最近几年才出了一个 MinGW 版本。所以 HiEasyX 从一开始也没打算支持 MinGW。
2. 本人因为从一开始就是用的 VS，且 VS 足够强大，所以没用过 MinGW、不了解 MinGW。
3. 将 HiEasyX 适配 MinGW 可能是一个大工程，即使我会 MinGW，也未必能有足够的时间去做。

所以就目前来看，HiEasyX 应该还不会适配 MinGW，最好是用 VS。不过，我也期待有人能将 HiEasyX 适配到 MinGW，那样就可以方便更多用户了。

**Comment by F1A-in-wonder** [comment]
thanks

**Comment by Alan-CRL** [comment]
好消息：HiEasyX 正在重写，将同时支持 MBCS 和 UNICODE，MinGW 和 TDM 也将适配，新版本将于稍后推出。

**Comment by Alan-CRL** [comment]
> 什么时候可以支持MinGW编译器啊（期待）

> 同求

好消息：HiEasyX 现已同时支持 Unicode 和 MBCS 字符集，同时支持 MSVC、MinGW、TDM-GCC 等编译器
