### ISSUE TITLE
[ 问题反馈 ] edit.PreSetStyle(true, false, true, true, true, true)时报错

### ISSUE THREAD

**Issue by Satan123231** [zouhuidong/HiEasyX#15]
![image](https://user-images.githubusercontent.com/41412981/218266939-01d537b9-c679-4170-8048-66a513546aee.png)
参考教程，使用该行代码时报错：
![image](https://user-images.githubusercontent.com/41412981/218266962-5cb121c7-0186-43d5-9031-657081c48b1a.png)

**Comment by zouhuidong** [comment]
codebus 的教程更新有延迟，请看 github 上的最新教程。控件的章节请看：https://github.com/zouhuidong/HiEasyX/blob/main/Tutorial/ctrl_sys.md
