### ISSUE TITLE
Canvas画布可以设置设置坐标原点么

### ISSUE THREAD

**Issue by WWNNL** [zouhuidong/HiEasyX#17]
Canvas画布可以设置设置坐标原点么

**Comment by zouhuidong** [comment]
不可以，EasyX 中的 IMAGE 也不可以设置绘图坐标原点，坐标原点的概念是对于绘图设备，即绘图窗口来说的。

**Comment by Alan-CRL** [comment]
@BWHXing 似乎你并不需要在使用Canvas时设置坐标原点，我们可以通常将需要绘制的内容从 0,0 开始绘制，只需调整输出到绘图窗口的坐标即可
