### ISSUE TITLE
宏定义问题导致编译不通过

### ISSUE THREAD

**Issue by Psertded** [zouhuidong/HiEasyX#2]
![image](https://user-images.githubusercontent.com/110461934/185772902-4a02c123-5669-42b2-8fe3-0af4f48f561a.png)
GetHWnD被宏定义定义为:HiEasyX::GetHWnD
导致编译不通过

**Comment by Psertded** [comment]
已解决:在所有include之后再#include "HiEasyX.h"

**Comment by zouhuidong** [comment]
是的，可以这样解决，但是这意味着前面的包含的头文件不使用 HiEasyX。
在 HiEasyX 中，窗口的管理工作由 HiEasyX 完成，而获取窗口句柄的函数是 `hiex::GetHWnd_win32` 。
如果使用了 EasyX 原生的 `GetHWnd` 函数，则建议不要再混用 HiEasyX 的窗口（实际可行，但建议不要这么做）。

如果想直接屏蔽 HiEasyX 的扩展窗口功能，请在 HiDef.h 中定义 `_NATIVE_EASYX_`。
