### ISSUE TITLE
HiEasyX如何在code::blocks里配置

### ISSUE THREAD

**Issue by hxyh666** [zouhuidong/HiEasyX#20]
请求回复

**Comment by zouhuidong** [comment]
回复晚，抱歉。
HiEasyX 目前只能在 VS 中使用（MSVC 编译器），而 CodeBlocks 使用的是 MinGW 编译器，所以 HiEasyX 暂时不支持在 CodeBlocks 中使用。关于这个问题，请参见 #14，感谢支持。

**Comment by Alan-CRL** [comment]
好消息：HiEasyX 现已同时支持 Unicode 和 MBCS 字符集，同时支持 MSVC、MinGW、TDM-GCC 等编译器
